name: Build and deploy container app to Azure Web App - docker-laravel-demo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Copy .env file
        run: cp .env docker-azure-cicd/

      - name: Generate App Key
        run: php artisan key:generate --show
        id: key

      - name: Update .env with App Key
        run: echo "APP_KEY=${{ steps.key.outputs.result }}" >> docker-azure-cicd/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://dockerlaravelregistry.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_b5fe8ab3a7a045bfa02e1895abe00dae }}
          password: ${{ secrets.AzureAppService_ContainerPassword_8e1b0a1e6935497388dd128a4375696f }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: dockerlaravelregistry.azurecr.io/laravelapidemo:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "docker-laravel-demo"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1f70fafb2450496aa2ecfbe13f40bb62 }}
          images: "dockerlaravelregistry.azurecr.io/laravelapidemo:${{ github.sha }}"
